# Github login name of the bot itself
botUserLogin: bf2-arch-test

# The time, in hours, to wait between checking for stalled discussions
# 1440 minutes = 24 hours
stalledDiscussionPollTimeMins: 1440

